
# http://travis-ci.org/mpi4py/mpi4py

language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

env:
    - NUMPY_VERSION=1.8 

cache:
    directories:
        - $HOME/rainwoodman/pfft-python/build/depends

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py
    - if [ $TRAVIS_PYTHON_VERSION == 2.6 ]; then conda install --yes argparse; fi
    - python setup.py install > build.log

script:
    - mpirun -n 1 python $PWD/tests/roundtrip.py -v -Nmesh 13 15 16
    #- mpirun -n 4 python $PWD/tests/roundtrip.py -v -Nmesh 13 15 16

#notifications:
#  email: false
